### ISSUE TITLE
Where did you find the dataset for this program?

### ISSUE THREAD

**Issue by raghutiwari** [Zhanelya/Big-Data-Project#1]

**Comment by Zhanelya** [comment]
Hi, it was provided to us as part of the course in university.

**Comment by raghutiwari** [comment]
Can you share that with us? I could really use your help.

Thank you.
Raghu Tiwari

**Comment by Zhanelya** [comment]
I am sorry, I don't have a copy of the dataset, as it was installed on university machines. And it was almost 3 years ago as well. You can try to contact Big Data dept at Queen Mary University if interested.

**Comment by Zhanelya** [comment]
You can try to google different twitter datasets tp find something similar. E.g https://data.world/datasets/twitter

**Comment by raghutiwari** [comment]
Thank you for your help.
